image: gradle:alpine

stages:
  - build
  - test
  - deploy

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - sudo ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - sudo ./gradlew check

deploy:
  stage: deploy
  script:
    - sudo docker kill smallpro
    - sudo docker rm smallpro
    - sudo docker build -t small-procurement-system-backend:latest .
    - sudo docker run -d -p 8080:8080 --name smallpro small-procurement-system-backend:latest
