version: '3'  
services:
    springbootapp:
        image: miniprocurements/backend:latest
        container_name: miniprocurements
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8080
        ports:
            - 8080:8080
