version: '3'  
services:
    springbootapp:
        image: miniprocurements/backend:latest
        container_name: miniprocurements
        expose:
            - 8080
        ports:
            - 8080:8080
        volumes:
        -   procurements_vol:/procurements/files
volumes:
    procurements_vol:
        external: false
